// Copyright (c) Pascal Brand
// MIT License

import fs from 'fs'
import path from 'path'
import sharp from 'sharp'

const config = {
  srcDir: 'data',
  inputExtension: ['.png', /* '.webp' */],

  output: {
    sprites: ['tmp/astro-sprite.png', 'tmp/astro-sprite.webp'],
    css: {
      output: 'tmp/astro-sprite.css',
      cssPrefix: '.astro-sprite-',
      cssSelector: '::before',
    }
  }
}

let srcFiles = []
await Promise.all(fs.readdirSync(config.srcDir).map(async (file) => {
  const fullName = path.join(config.srcDir, file);
  if (fs.statSync(fullName).isFile()) {
    // it is a file. Checks it ends with inputExtension
    if (config.inputExtension.some(ext => file.endsWith(ext))) {
      const image = sharp(fullName);
      const metadata = await image.metadata()
      srcFiles.push( { name: path.parse(file).name, fullName, width: metadata.width, height: metadata.height, } )
    }
  }
}))

let cssText = '/* Auto-generated by astro-sprite */\n'
let positions = []
let left = 0
let height = 0
srcFiles.forEach(src => {
  cssText += `${config.output.css.cssPrefix}${src.name}${config.output.css.cssSelector} { background-position: -${left}px -0px; width: ${src.width}px; height: ${src.height}px; }\n`
  positions.push({ input: src.fullName, left: left, top: 0 })
  left += src.width
  if (height < src.height) {
    height = src.height
  }
})
fs.writeFileSync(config.output.css.output, cssText)

const sprite = sharp({
  create: {
    background: { alpha: 0, b: 0, g: 0, r: 0 },
    channels: 4,
    height: height,
    width: left,
  },
});

sprite.composite(positions);
config.output.sprites.forEach(output =>
  sprite.toFile(output)
)


console.log(srcFiles)
console.log(cssText)
console.log('DONE')
